[package]
name = "Streamdeck-CLI"
version = "0.1.0"
edition = "2021"

[dependencies]
elgato-streamdeck = { path = "/home/teras/Sources/elgato-streamdeck" }
indexmap = "2.6.0"
image = { version = "0.25.2", default-features = false, features = [
    "bmp",
    "jpeg",
] }